require_relative 'file_parser'
require_relative 'browser_display'
require_relative 'terminal_display'
require_relative 'person'
require_relative 'record'
require_relative 'record_list'
require_relative 'sort_list'
require_relative '../../config'
